name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-stringr
  - pip
  - pip:
    - seaborn
    - matplotlib
    - pandas
    - scikit-learn
    - plotly
    - numpy
    - statsmodels
    
    
